internalName: _keyboard

locales:
  en:
    name: &bundleName " Keyboards"
    description: "Mobile OS keyboards for  languages from the Divvun group at UiT."
  nb:
    name: " tastatur"
    description: "Mobiltastatur for  fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2016 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [kpv]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.__COLLECTION__
    icon: sami-icon.pdf
    keyStore: /Users/brendan/git/softkbdgen/test.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "iOS Development"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.__COLLECTION__
    bundleName: *bundleName
    icon:
        90: sami-icon-small.png
        150: sami-icon.png
  osx: *AppleID
