internalName: kpv_keyboard

locales:
  en:
    name: &bundleName "Komi-Zyrian Keyboards"
    description: "Mobile OS keyboards for the Komi-Zyrian language from the Divvun group at UiT."
  nb:
    name: "Komi-Zyrian tastatur"
    description: "Mobiltastatur for Komi-Zyrian fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [kpv]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.kpv
    icon: images/kpv-icon.pdf
    keyStore: /Users/brendan/git/softkbdgen/test.keystore
    keyAlias: kpv_keyboard

  ios: &AppleID
    codeSignId: "iOS Development"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.kpv
    bundleName: *bundleName
    icon: images/kpv-icon.png
  osx:
    <<: *AppleID
    icon: images/kpv-keyboard-menu-icon.png
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
