locales:
  en:
    name: Komi-Zyrian Keyboards
    description: >-
      Mobile OS keyboards for the Komi-Zyrian language from the Divvun group at
      UiT
  nb:
    name: Komisyrjensk tastatur
    description: Mobiltastatur for komisyrjensk fra Divvun-gruppa
  kpv:
    name: Коми-зырян кыв
    description: Mobiltastatur for komisyrjensk fra Divvun-gruppa
  fi:
    name: Komisyrjääni
    description: Mobiltastatur for komisyrjensk fra Divvun-gruppa
  ru:
    name: Коми-зырянский язык
    description: Mobiltastatur for komisyrjensk fra Divvun-gruppa

author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
