locales:
  en:
    name: Komi-Zyrian Keyboards
    description: >-
      Mobile OS keyboards for the Komi-Zyrian language from the Divvun group at
      UiT.
  nb:
    name: Komi-Zyrian tastatur
    description: Mobiltastatur for Komi-Zyrian fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
