template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 25
template_sha = "9082f449e365b13a665769d5a7dc9dd665d8f729"

[replacements]
__UND2C__ = "kpv"
__UNDEFINED__ = "Komi-Zyrian"
__UND__ = "kpv"
