template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 5
template_sha = "c78613bb3fe4a8c35f6719494f51fe9f4013486c"

[replacements]
__UND2C__ = "kpv"
__UNDEFINED__ = "Komi-Zyrian"
__UND__ = "kpv"
