template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 21
template_sha = "bf03bea23dae0e7fdd47b4e78826e30f87b79dbb"

[replacements]
__UND2C__ = "kpv"
__UNDEFINED__ = "Komi-Zyrian"
__UND__ = "kpv"
