template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 33
template_sha = "7bd78e141ef2a9cbd0bad5887f79301c4cd034f5"

[replacements]
__UND2C__ = "kpv"
__UNDEFINED__ = "Komi-Zyrian"
__UND__ = "kpv"
