template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 6
template_sha = "ebfffb4d3630c8dae1c5b61dc92850d1513a17ed"

[replacements]
__UND2C__ = "kpv"
__UNDEFINED__ = "Komi-Zyrian"
__UND__ = "kpv"
