template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 30
template_sha = "c2ac7ff58b85b431abb11163c7cdf93f36e336e5"

[replacements]
__UND2C__ = "kpv"
__UNDEFINED__ = "Komi-Zyrian"
__UND__ = "kpv"
