template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 29
template_sha = "159cf3b8a769e4f912313925bcbc97154310b864"

[replacements]
__UND2C__ = "kpv"
__UNDEFINED__ = "Komi-Zyrian"
__UND__ = "kpv"
