template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 7
template_sha = "2b5a1f7512a3079a2b0d4795567a31e32bcd33fe"

[replacements]
__UND2C__ = "kpv"
__UNDEFINED__ = "Komi-Zyrian"
__UND__ = "kpv"
