template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 13
template_sha = "1b5b88d9032b23b1a4bcfe3ee7a1dffe14303e73"

[replacements]
__UND2C__ = "kpv"
__UNDEFINED__ = "Komi-Zyrian"
__UND__ = "kpv"
