theme: jekyll-theme-giellalt
title: Komi-Zyrian Keyboards
description: Keyboard layout definitions for desktop and mobile OS's

defaults:
  - scope: { path: "" }
    values:
      layout: keyboard

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
