remote_theme: giellalt/jekyll-theme-giellalt@main
title: Komi-Zyrian Keyboards
description: Keyboard layout definitions for desktop and mobile OS's
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jemoji

defaults:
  - scope: { path: "" }
    values:
      layout: keyboard

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
