name: Docs
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: keyboard
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r docs/requirements.txt
        working-directory: keyboard
      - name: Generate layout documentation
        run: python docs/scripts/generate-layout-docs.py
        working-directory: keyboard
      - name: deploy gh pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: keyboard/docs/
          enable_jekyll: true
